### PR TITLE
[vue3]: migrate package to Vue 3

### PR DESCRIPTION
**Pull request by Antreesy**
- Ref #1201

Bump and audit dependencies:
- Related:
  - `vue`
  - `@nextcloud/vue`
  - `@nextcloud/vite-config`

Migrate to Vue3:
- replace `Vue.set` syntax
- remove unused arguments

Tested with Talk vue3 branch:
image

### CODE REVIEW

**Comment by Antreesy** [comment]
Perhaps I was a little hasty here. We can decide whether to:
- release 0.13.0 directly from the `vue3` branch (straight away),
- or merge it into `master` first and do a release (this PR).

Given that this library is not very popular and is rarely updated, I would prefer the second option

**Comment by susnux** [comment]
> release 0.13.0 directly from the `vue3` branch (straight away),

Probably better doing a major bump?

**Review by st3iny — COMMENTED** [review]
Looks good, but I'd also prefer a major bump.

**Comment by ShGKme** [comment]
> * release 0.13.0 directly from the `vue3` branch (straight away),

This would trigger dependabot and result in an invalid bump

**Comment by ShGKme** [comment]
We can release it as `v2` to have one major version just in case for breaking change in vue 2.

**Comment by susnux** [comment]
> We can release it as v2 to have one major version just in case for breaking change in vue 2.

I do not think we need another major for vue2, as this basically sticks with 0.x anyways :sweat_smile:

**Comment by Antreesy** [comment]
Rebased onto release branch (for now)
After `0.13.0` release and approval:
- [ ] merge PR to `master`
- [ ] release `1.0.0`, add comment to README.md about versions compatibility

**Comment by ShGKme** [comment]
Then let's branch of the current `master` as `stable0` and then merge this to `master` and release as `v1.0.0`.

Releasing as `v0.x` will likely trigger dependabot/renovate as a valid safe upgrade.

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Rebased and tested, seems to work find :)

**Comment by Antreesy** [comment]
> Rebased and tested, seems to work find :) 

Shall we note in Readme, that this version is for Vue3 now?

**Comment by susnux** [comment]
> Shall we note in Readme, that this version is for Vue3 now?

Yes sounds good

**Pull request merged**
